"""empty message

Revision ID: 9ceecf9b3c8f
Revises: da78cb7f0474
Create Date: 2020-11-16 20:30:59.537435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ceecf9b3c8f'
down_revision = 'da78cb7f0474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ips_matched', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('ips_resolved', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('search_expression', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'value')
    op.drop_column('jobs', 'search_expression')
    op.drop_column('jobs', 'ips_resolved')
    op.drop_column('jobs', 'ips_matched')
    # ### end Alembic commands ###
