"""empty message

Revision ID: c97f816dee11
Revises: 9ceecf9b3c8f
Create Date: 2020-11-17 18:58:54.193111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97f816dee11'
down_revision = '9ceecf9b3c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ips_received', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ips_received')
    # ### end Alembic commands ###
